### ISSUE TITLE
is Jenkins 2.401.1  podTemplate image support jdk8

### ISSUE THREAD

**Issue by kingui1106** [jenkinsci/docker-inbound-agent#362]
### Describe your use-case which is not covered by existing documentation.

Jenkins 2.401.1 using helm install.

I want to specify an image for jdk8.
Because my code needs to be compiled under jdk8.
But I try some images, The pod cannot start properly.

Is there any solution.Thanks!

this is my jenkinsfile.
```
def label = "build-testserverone-${UUID.randomUUID().toString()}"
podTemplate(
    cloud: "kubernetes",
    namespace: "jenkins", 
    label: label,
    containers: [
        containerTemplate(
            name: "jnlp",
            image: "xxxx"
        ),
    ]
) 
```

**Comment by dduportal** [comment]
Hi @kingui1106 , as JDK8 was dropped by the Jenkins controller in 2022 (ref. https://www.jenkins.io/blog/2022/06/28/require-java-11/), JDK11 is the default (with JDK17 possibly used).

Jenkins project [recommends](https://www.jenkins.io/doc/administration/requirements/java/) that the exact same JDK should be used to execute agent process and the controller: this is the reason why we dropped the JDK8 from the agent Docker image (providing the same JDK11 and JDK17 as the controller image).

That being said, Jenkins keep supporting executing jobs with any JDK you need, such as the JDK8 in your case: the constraints I described above is only for executing the Jenkins agent process.

There is no problem to have your own image with multiple JDKs in the agent template and you can select the required JDK when building by defining the `JAVA_HOME` environment variable, while specifying something else for the agent process with `JENKINS_JAVA_BIN` environment variable.

Here is an example from ci.jenkins.io (JCasc configuration for the Linux pod template for `maven jdk8` agents):

```
- name: "jnlp-maven-8"
  label: "container kubernetes cik8s maven maven-8 jdk8"
  containers:
  - name: "jnlp"
    image: "jenkinsciinfra/jenkins-agent-ubuntu-22.04@sha256:48a7e6876fbadf11146aa0e554bc01ccb1106a5d1d4c4a61afadb1438b322816"
    command: "/usr/local/bin/jenkins-agent"
    envVars:
    - envVar:
        key: "JENKINS_JAVA_OPTS"
        value: "-XX:+PrintCommandLineFlags"
    - envVar:
        key: "JENKINS_JAVA_BIN"
        value: "/opt/jdk-11/bin/java"
    - envVar:
        key: "JAVA_HOME"
        value: "/opt/jdk-8"
    - envVar:
        key: "PATH"
        value: "/opt/jdk-8/bin:/home/jenkins/.asdf/shims:/home/jenkins/.asdf/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
    - envVar:
        key: "ARTIFACT_CACHING_PROXY_PROVIDER"
        value: "aws"
    livenessProbe:
      failureThreshold: 0
      initialDelaySeconds: 0
      periodSeconds: 0
      successThreshold: 0
      timeoutSeconds: 0
    resourceLimitCpu: "4"
    resourceLimitMemory: "8G"
    resourceRequestCpu: "4"
    resourceRequestMemory: "8G"
    workingDir: "/home/jenkins/agent"
  slaveConnectTimeout: 100
  slaveConnectTimeoutStr: "100"
  volumes:
  - emptyDirVolume:
      memory: true
      mountPath: "/tmp"
  - emptyDirVolume:
      memory: false
      mountPath: "/home/jenkins/.m2/repository"
  yamlMergeStrategy: "override"
```

This example specifies the JDK11 installed in /opt/jdk-11 to be used for the agent while /opt/jdk-8 is defined for the jobs running on the machine.


The main task for you is to decide either you maintain your own docker image  from `jenkins/inbound-agent:jdk11` to add the exact JDK8 you want, or if you want to use "Jenkins -> Manage Jenkins -> Tools" section to specify a "JDK8 tool" and then update your pipeline to call the `tool` step, or eventually your pipeline could specify the JAVA_HOME env var themselves.
