### ISSUE TITLE
Root directory not writable: /home/jenkins/.jenkins/cache/jars

### ISSUE THREAD

**Issue by hanrw** [jenkinsci/docker-inbound-agent#52]
```
version: '2'
services:
  jenkinsci-slave5:
    image: jenkinsci/jnlp-slave
    environment:
      JENKINS_AGENT_NAME: jenkins-slave
      JENKINS_SECRET: fac1f848bf46d90440979a3e9914f5e412b49b7ebf1fe0adc4bfa2ad2fcd349b
      JENKINS_URL: master
    volumes:
    - /home/jenkins/slave-1-home:/home/jenkins
    - /home/jenkins/m2/repository:/home/.m2/repository
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: alway
```
We are want keep the data to the same place.
But it's got exception when we mount volume on it.

**Comment by oleg-nenashev** [comment]
Which Remoting version do you use? It may be a case for 3.8 or something, but it should not happen on Remoting 3.14

**Comment by MadeInChina** [comment]
Thanks. @oleg-nenashev 
It's the previous version not sure if or not 3.8 and now working since updated to latest version.

**Comment by MadeInChina** [comment]
Building remotely on jenkins-slave-4 (default) in workspace /home/jenkins/workspace/xxxxxx
java.io.IOException: Failed to mkdirs: /home/jenkins/workspace/xxxxxx
	at hudson.FilePath.mkdirs(FilePath.java:1170)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1200)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
	at hudson.model.Run.execute(Run.java:1724)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:542)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)

Finished: FAILURE

```
jenkins-slave-4:
    image: jenkinsci/jnlp-slave
    environment:
      JENKINS_AGENT_NAME: jenkins-slave-4
      JENKINS_URL: https://ci2.finnplay.net/
      JENKINS_SECRET: ab9f27798100418590c07a910f299e5e2e250eb1d79c5858a75b7f8e24a8f1f2
      JENKINS_AGENT_WORKDIR: /home/jenkins/agent/
    stdin_open: true
    volumes:
    - /home/jenkins/slave-4-home/:/home/jenkins
    - /home/jenkins/m2/repository:/home/jenkins/.m2/repository
    - /home/jenkins/tools:/home/jenkins/tools
    tty: true
    labels:
      io.rancher.container.pull_image: always
```

**Comment by oleg-nenashev** [comment]
@MadeInChina Likely there is a permission error. Note that...

* Agent work DIR is /home/jenkins/agent/
* Agent remote DIR in agent config is  /home/jenkins/ (according to " /home/jenkins/workspace/xxxxxx")

https://issues.jenkins-ci.org/browse/JENKINS-47324 should improve the error messages.

**Comment by MadeInChina** [comment]
Hi @oleg-nenashev, could that be expose internalDir(JENKINS_AGENT_INTERNAL_DIR) path same as JENKINS_AGENT_WORKDIR which should fix that issue.? 

```
Run from agent command line:

java -jar agent.jar -jnlpUrl https://ci/computer/jenkins-slave-4/slave-agent.jnlp -secret ab9f27798100418590c07a910f299e5e2e250eb1d79c5858a75b7f8e24a8f1f2 -workDir "/home/jenkins" -internalDir "internal"

jenkins-slave-4:
    image: jenkinsci/jnlp-slave
    environment:
      JENKINS_AGENT_NAME: jenkins-slave-4
      JENKINS_URL: master
      JENKINS_SECRET: ab9f27798100418590c07a910f299e5e2e250eb1d79c5858a75b7f8e24a8f1f2
      JENKINS_AGENT_WORKDIR: /home/jenkins/agent/
      JENKINS_AGENT_INTERNAL_DIR: internal
    stdin_open: true
    volumes:
    - /home/jenkins/slave-4-home/:/home/jenkins
    - /home/jenkins/m2/repository:/home/jenkins/.m2/repository
    - /home/jenkins/tools:/home/jenkins/tools
    tty: true
    labels:
      io.rancher.container.pull_image: always
```
